### ISSUE TITLE
Pictures are not uploaded

### ISSUE THREAD

**Issue by Tnick0** [Eg3-git/wad2project#22]
Uploading pictures via forms is not working for some reason. I can't figure out why, but I think it has to do with views.py

**Comment by FilipVyrostko** [comment]
Do you have media dir. created, if so, is it at correct level ?

**Comment by Tnick0** [comment]
Weird. It's loading the default images for user profiles and movie covers but I cannot change them. But if it's my issue maybe I've done something wrong.

**Comment by FilipVyrostko** [comment]
You were right there was a problem with edit functions. Good call.
